version: '3.9'

services: 
    postgres-test:
        image: postgres
        environment:
            POSTGRES_PASSWORD: senha123
            POSTGRES_DB: 1STi_test
        ports: 
            - 5432:5432

    redis-test:
        image: redis
        ports:
            - 6379:6379
